management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: "*" # Expose all endpoints

server:
  port: 8080
  compression:
    enabled: true
    min-response-size: 2048
    mime-types: application/json,application/xml,text/html,text/plain
  servlet:
    context-path: /api